language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run buildprod; echo "brandapplause.com" > dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  repo: BrandApplause/BrandApplause.github.io
  target_branch: master
  on:
    branch: master
